### ISSUE TITLE
Non Uniform Frontend Designs

### ISSUE THREAD

**Issue by dheerazsah** [Acharya123himal/Tax-Calculator-System#1]
The frontend designs are not uniform, changes should be made in the designs. 
Please, re-visit your work and make use to follow  the rules which we discussed in team meetings.
I have listed below the design format to follow for uniform design. Also make sure not to use any color. I have found a 
colored design in Forgot Password Page.

Design Format
Color: Black and White
Color Code: Black - #000000
                    White - #FFFFFF
Font: Roboto Family
         Heading: Bold (700)
         Sub-Heading: Semi-bold (500)
         Text: Light (300)
Layout: Rounded Rectangle

**Comment by Acharya123himal** [comment]
Done
