### ISSUE TITLE
Header and footer sections are not properly aligned.

### ISSUE THREAD

**Issue by HimalBudhathoki** [Acharya123himal/Tax-Calculator-System#4]
The header section text is not properly aligned so it is not looking too good. Please align these elements in the same line to make the header section more attractive and functional.
Also, the gap or empty space is more in the footer area and the privacy policy section is not in the bottom of the page. Please, decrease the blank space of the footer area to make the footer attractive and put the privacy policy section at the left bottom of the footer.

**Comment by Acharya123himal** [comment]
completed
