### ISSUE TITLE
Result page and inner texts are not properly aligned and the cross mark is missing on the top right part of result page.

### ISSUE THREAD

**Issue by HimalBudhathoki** [Acharya123himal/Tax-Calculator-System#6]
When we enter the big number while calculating tax the result page cannot handle that type of number and overlap into the heading. Due to this reason the inner texts overlap and cannot align properly in the page. So fix this problem and make a properly functionable result page.
Also, The result page is too big which makes it difficult to print the full result page properly. As we discussed in our team meeting, our wireframe says the result page is half of the screen and seems more attractive than the full page which makes it easy while printing this page. So please put this page in the middle and fit it to the screen.

**Comment by Acharya123himal** [comment]
we have finished
